-- SQL file to insert country data into the countries table
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (1, 'http://example.com/flags/afghanistan.png', 'Afghanistan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (2, 'http://example.com/flags/albania.png', 'Albania');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (3, 'https://www.countryflags.com/wp-content/uploads/flag-jpg-xl-3-scaled.jpg', 'Algeria');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (4, 'http://example.com/flags/angola.png', 'Angola');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (5, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/True_South_Antarctic_Flag.svg/1600px-True_South_Antarctic_Flag.svg.png', 'Antarctica');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (6, 'http://example.com/flags/argentina.png', 'Argentina');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (7, 'http://example.com/flags/armenia.png', 'Armenia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (8, 'https://www.countryflags.com/wp-content/uploads/flag-jpg-xl-10-scaled.jpg', 'Australia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (9, 'http://example.com/flags/austria.png', 'Austria');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (10, 'http://example.com/flags/azerbaijan.png', 'Azerbaijan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (11, 'http://example.com/flags/bahamas.png', 'Bahamas');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (12, 'http://example.com/flags/bangladesh.png', 'Bangladesh');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (13, 'http://example.com/flags/belarus.png', 'Belarus');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (14, 'http://example.com/flags/belgium.png', 'Belgium');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (15, 'http://example.com/flags/belize.png', 'Belize');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (16, 'http://example.com/flags/benin.png', 'Benin');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (17, 'http://example.com/flags/bhutan.png', 'Bhutan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (18, 'http://example.com/flags/bolivia.png', 'Bolivia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (19, 'http://example.com/flags/bosnia_and_herzegovina.png', 'Bosnia and Herz.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (20, 'http://example.com/flags/botswana.png', 'Botswana');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (21, 'https://cdn.countryflags.com/thumbs/brazil/flag-square-500.png', 'Brazil');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (22, 'http://example.com/flags/brunei.png', 'Brunei');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (23, 'http://example.com/flags/bulgaria.png', 'Bulgaria');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (24, 'http://example.com/flags/burkina_faso.png', 'Burkina Faso');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (25, 'http://example.com/flags/burundi.png', 'Burundi');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (26, 'http://example.com/flags/cambodia.png', 'Cambodia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (27, 'http://example.com/flags/cameroon.png', 'Cameroon');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (28, 'https://cdn.countryflags.com/thumbs/canada/flag-square-500.png', 'Canada');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (29, 'http://example.com/flags/central_african_republic.png', 'Central African Rep.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (30, 'http://example.com/flags/chad.png', 'Chad');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (31, 'http://example.com/flags/chile.png', 'Chile');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (32, 'https://cdn.countryflags.com/thumbs/china/flag-square-500.png', 'China');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (33, 'http://example.com/flags/colombia.png', 'Colombia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (34, 'http://example.com/flags/congo.png', 'Congo');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (35, 'http://example.com/flags/costa_rica.png', 'Costa Rica');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (36, 'http://example.com/flags/croatia.png', 'Croatia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (37, 'http://example.com/flags/cuba.png', 'Cuba');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (38, 'http://example.com/flags/cyprus.png', 'Cyprus');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (39, 'http://example.com/flags/czech_republic.png', 'Czech Rep.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (40, 'https://cdn.countryflags.com/thumbs/cote-d-ivoire/flag-square-500.png', 'Côte d''Ivoire');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (41, 'http://example.com/flags/democratic_republic_of_congo.png', 'Dem. Rep. Congo');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (42, 'http://example.com/flags/democratic_republic_of_korea.png', 'Dem. Rep. Korea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (43, 'http://example.com/flags/denmark.png', 'Denmark');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (44, 'http://example.com/flags/djibouti.png', 'Djibouti');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (45, 'http://example.com/flags/dominican_republic.png', 'Dominican Rep.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (46, 'http://example.com/flags/ecuador.png', 'Ecuador');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (47, 'http://example.com/flags/egypt.png', 'Egypt');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (48, 'http://example.com/flags/el_salvador.png', 'El Salvador');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (49, 'http://example.com/flags/equatorial_guinea.png', 'Eq. Guinea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (50, 'http://example.com/flags/eritrea.png', 'Eritrea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (51, 'http://example.com/flags/estonia.png', 'Estonia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (52, 'http://example.com/flags/ethiopia.png', 'Ethiopia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (53, 'http://example.com/flags/falkland_islands.png', 'Falkland Is.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (54, 'http://example.com/flags/fiji.png', 'Fiji');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (55, 'http://example.com/flags/finland.png', 'Finland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (56, 'http://example.com/flags/french_southern_territories.png', 'Fr. S. Antarctic Lands');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (57, 'http://example.com/flags/france.png', 'France');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (58, 'http://example.com/flags/gabon.png', 'Gabon');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (59, 'http://example.com/flags/gambia.png', 'Gambia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (60, 'http://example.com/flags/georgia.png', 'Georgia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (61, 'https://www.countryflags.com/wp-content/uploads/germany-flag-png-large.png', 'Germany');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (62, 'http://example.com/flags/ghana.png', 'Ghana');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (63, 'http://example.com/flags/greece.png', 'Greece');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (64, 'http://example.com/flags/greenland.png', 'Greenland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (65, 'http://example.com/flags/guatemala.png', 'Guatemala');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (66, 'http://example.com/flags/guinea.png', 'Guinea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (67, 'http://example.com/flags/guinea_bissau.png', 'Guinea-Bissau');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (68, 'http://example.com/flags/guyana.png', 'Guyana');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (69, 'http://example.com/flags/haiti.png', 'Haiti');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (70, 'http://example.com/flags/honduras.png', 'Honduras');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (71, 'http://example.com/flags/hungary.png', 'Hungary');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (72, 'http://example.com/flags/iceland.png', 'Iceland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (73, 'https://cdn.countryflags.com/thumbs/india/flag-square-500.png', 'India');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (74, 'https://cdn.countryflags.com/thumbs/indonesia/flag-square-500.png', 'Indonesia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (75, 'http://example.com/flags/iran.png', 'Iran');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (76, 'http://example.com/flags/iraq.png', 'Iraq');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (77, 'http://example.com/flags/ireland.png', 'Ireland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (78, 'http://example.com/flags/israel.png', 'Israel');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (79, 'https://www.countryflags.com/wp-content/uploads/italy-flag-png-large.png', 'Italy');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (80, 'http://example.com/flags/jamaica.png', 'Jamaica');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (81, 'http://example.com/flags/japan.png', 'Japan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (82, 'http://example.com/flags/jordan.png', 'Jordan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (83, 'http://example.com/flags/kazakhstan.png', 'Kazakhstan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (84, 'http://example.com/flags/kenya.png', 'Kenya');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (85, 'http://example.com/flags/korea.png', 'Korea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (86, 'http://example.com/flags/kosovo.png', 'Kosovo');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (87, 'http://example.com/flags/kuwait.png', 'Kuwait');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (88, 'http://example.com/flags/kyrgyzstan.png', 'Kyrgyzstan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (89, 'http://example.com/flags/lao_pdr.png', 'Lao PDR');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (90, 'http://example.com/flags/latvia.png', 'Latvia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (91, 'http://example.com/flags/lebanon.png', 'Lebanon');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (92, 'http://example.com/flags/lesotho.png', 'Lesotho');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (93, 'http://example.com/flags/liberia.png', 'Liberia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (94, 'http://example.com/flags/libya.png', 'Libya');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (95, 'http://example.com/flags/lithuania.png', 'Lithuania');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (96, 'http://example.com/flags/luxembourg.png', 'Luxembourg');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (97, 'http://example.com/flags/macedonia.png', 'Macedonia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (98, 'http://example.com/flags/madagascar.png', 'Madagascar');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (99, 'http://example.com/flags/malawi.png', 'Malawi');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (100, 'http://example.com/flags/malaysia.png', 'Malaysia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (101, 'http://example.com/flags/mali.png', 'Mali');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (102, 'http://example.com/flags/mauritania.png', 'Mauritania');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (103, 'http://example.com/flags/mexico.png', 'Mexico');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (104, 'http://example.com/flags/moldova.png', 'Moldova');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (105, 'http://example.com/flags/mongolia.png', 'Mongolia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (106, 'http://example.com/flags/montenegro.png', 'Montenegro');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (107, 'http://example.com/flags/morocco.png', 'Morocco');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (108, 'http://example.com/flags/mozambique.png', 'Mozambique');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (109, 'http://example.com/flags/myanmar.png', 'Myanmar');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (110, 'http://example.com/flags/north_cyprus.png', 'N. Cyprus');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (111, 'http://example.com/flags/namibia.png', 'Namibia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (112, 'http://example.com/flags/nepal.png', 'Nepal');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (113, 'http://example.com/flags/netherlands.png', 'Netherlands');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (114, 'http://example.com/flags/new_caledonia.png', 'New Caledonia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (115, 'http://example.com/flags/new_zealand.png', 'New Zealand');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (116, 'http://example.com/flags/nicaragua.png', 'Nicaragua');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (117, 'http://example.com/flags/niger.png', 'Niger');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (118, 'http://example.com/flags/nigeria.png', 'Nigeria');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (119, 'http://example.com/flags/norway.png', 'Norway');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (120, 'http://example.com/flags/oman.png', 'Oman');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (121, 'https://cdn.countryflags.com/thumbs/pakistan/flag-square-500.png', 'Pakistan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (122, 'http://example.com/flags/palestine.png', 'Palestine');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (123, 'http://example.com/flags/panama.png', 'Panama');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (124, 'http://example.com/flags/papua_new_guinea.png', 'Papua New Guinea');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (125, 'http://example.com/flags/paraguay.png', 'Paraguay');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (126, 'http://example.com/flags/peru.png', 'Peru');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (127, 'http://example.com/flags/philippines.png', 'Philippines');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (128, 'http://example.com/flags/poland.png', 'Poland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (129, 'http://example.com/flags/portugal.png', 'Portugal');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (130, 'http://example.com/flags/puerto_rico.png', 'Puerto Rico');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (131, 'http://example.com/flags/qatar.png', 'Qatar');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (132, 'http://example.com/flags/romania.png', 'Romania');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (133, 'http://example.com/flags/russia.png', 'Russia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (134, 'http://example.com/flags/rwanda.png', 'Rwanda');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (135, 'http://example.com/flags/south_sudan.png', 'S. Sudan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (136, 'http://example.com/flags/saudi_arabia.png', 'Saudi Arabia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (137, 'http://example.com/flags/senegal.png', 'Senegal');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (138, 'http://example.com/flags/serbia.png', 'Serbia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (139, 'http://example.com/flags/sierra_leone.png', 'Sierra Leone');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (140, 'http://example.com/flags/slovakia.png', 'Slovakia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (141, 'http://example.com/flags/slovenia.png', 'Slovenia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (142, 'http://example.com/flags/solomon_islands.png', 'Solomon Is.');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (143, 'http://example.com/flags/somalia.png', 'Somalia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (144, 'http://example.com/flags/somaliland.png', 'Somaliland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (145, 'http://example.com/flags/south_africa.png', 'South Africa');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (146, 'https://www.countryflags.com/wp-content/uploads/spain-flag-png-large.png', 'Spain');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (147, 'https://cdn.countryflags.com/thumbs/sri-lanka/flag-square-500.png', 'Sri Lanka');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (148, 'http://example.com/flags/sudan.png', 'Sudan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (149, 'http://example.com/flags/suriname.png', 'Suriname');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (150, 'http://example.com/flags/eswatini.png', 'Swaziland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (151, 'https://www.countryflags.com/wp-content/uploads/sweden-flag-png-large.png', 'Sweden');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (152, 'https://www.countryflags.com/wp-content/uploads/switzerland-flag-png-large.png', 'Switzerland');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (153, 'http://example.com/flags/syria.png', 'Syria');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (154, 'http://example.com/flags/taiwan.png', 'Taiwan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (155, 'http://example.com/flags/tajikistan.png', 'Tajikistan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (156, 'http://example.com/flags/tanzania.png', 'Tanzania');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (157, 'https://www.countryflags.com/wp-content/uploads/thailand-flag-png-large.png', 'Thailand');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (158, 'http://example.com/flags/timor_leste.png', 'Timor-Leste');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (159, 'http://example.com/flags/togo.png', 'Togo');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (160, 'http://example.com/flags/trinidad_and_tobago.png', 'Trinidad and Tobago');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (161, 'http://example.com/flags/tunisia.png', 'Tunisia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (162, 'http://example.com/flags/turkey.png', 'Turkey');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (163, 'http://example.com/flags/turkmenistan.png', 'Turkmenistan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (164, 'http://example.com/flags/uganda.png', 'Uganda');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (165, 'http://example.com/flags/ukraine.png', 'Ukraine');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (166, 'http://example.com/flags/united_arab_emirates.png', 'United Arab Emirates');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (167, 'http://example.com/flags/united_kingdom.png', 'United Kingdom');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (168, 'https://cdn.countryflags.com/thumbs/united-states-of-america/flag-square-500.png', 'United States');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (169, 'http://example.com/flags/uruguay.png', 'Uruguay');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (170, 'http://example.com/flags/uzbekistan.png', 'Uzbekistan');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (171, 'http://example.com/flags/vanuatu.png', 'Vanuatu');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (172, 'http://example.com/flags/venezuela.png', 'Venezuela');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (173, 'http://example.com/flags/vietnam.png', 'Vietnam');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (174, 'http://example.com/flags/western_sahara.png', 'W. Sahara');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (175, 'http://example.com/flags/yemen.png', 'Yemen');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (176, 'http://example.com/flags/zambia.png', 'Zambia');
INSERT INTO countries (country_id, country_flag_url, country_name) VALUES (177, 'http://example.com/flags/zimbabwe.png', 'Zimbabwe');

INSERT INTO owner (user_name, id) VALUES ('user1',1);
INSERT INTO owner (user_name, id) VALUES ('user2',2);